name: Java CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Compile project
        run: find . -name "*.java" > sources.txt && javac @sources.txt

      - name: Run main class
        run: java inventarioTest
